### ISSUE TITLE
Object flow is same as object velocity in Nuscenes?

### ISSUE THREAD

**Issue by bbzh** [OpenDriveLab/OccNet#2]
Hi, 

Thanks for releasing the data. The supplementary material says that "we annotate the flow velocity of voxel based
on the 3D box velocity". Does this step simply take the object velocity in the Nuscenes ground truth, and rename it as the flow for each voxel in the object? Or is there any difference?

**Comment by tongwwt** [comment]
Yes. For the foreground voxel, the flow is determined by the 3D box velocity. For the background object, the flow is zero.

**Comment by cbiras** [comment]
@bbzh I know it has been a long time since you posted this issue, but I have a question about the flow annotations. I am trying to train a network that predicts the dynamic voxels in a scene, so I need to link annotated flow to annotated voxels. Do you remember if it's possible to link the flow with each voxel? I wasn't able to figure out the relation between the two looking at the arrays and didn't find any information on this. Thank you!
